var fragen=[
"Etwas, was Du an den Strand mitnimmst",
"Ein amerikanischer Präsident",
"Ein Politiker",
"Eine Rockband",
"Ein Rapper",
"Eine Automarke",
"Etwas, was Du mit Winter in Zusammenhang bringst",
"Etwas, was Du mit Sommer in Zusammenhang bringst",
"Ein Sportler",
"Eine Sportart",
"Ein Künstler",
"Eine Zeitschrift",
"Eine Tageszeitung",
"Ein Musikinstrument",
"Ein elektronisches Bauteil",
"Etwas, was im Badezimmer nicht fehlen darf",
"Ein Philosoph",
"Ein bekannter Schriftsteller",
"Ein Radiosender",
"Ein Fernsehsender",
"Ein Fernsehmoderator",
"Ein Snack",
"Etwas, was dick macht",
"Ein Teil des Autos",
"Eine Partei",
"Ein diktatorisch geführter Staat",
"Ein Verbrechen",
"Ein Fortbewegungsmittel",
"Eine Inselgruppe",
"Eine Stadt in Deutschland",
"Ein Gemälde",
"Eine Musikrichtung",
"Ein Tanz",
"Ein Kommunikationsmittel",
"Ein Speichermedium",
"Eine Hunderasse",
"Ein Tier, das fliegen kann",
"Etwas, was unter Gefängnisstrafe steht",
"Etwas lebensgefährliches",
"Etwas, was bei keiner Musikanlage fehlen darf",
"Eine Stadt in Amerika",
"Ein Staat in Europa",
"Ein Meerestier",
"Eine Sehenswürdigkeit",
"Ein Buchverlag",
"Eine Bücherreihe",
"Ein Roman",
"Eine Sprache",
"Ein Songtitel",
"Eine Raubkatze",
"Ein Parasit",
"Eine Eissorte",
"Ein Schlagerstar",
"Eine Pferderasse",
"Eine Hunderasse",
"Ein Verkehrsmittel",
"Eine Stoffart",
"Ein chemisches Element",
"Ein Schulfach",
"Ein Fluss in Europa",
"Eine Baumart",
"Ein Kleidungsstück",
"Eine Fernsehsendung",
"Ein Kabarettist",
"Ein Greifvogel",
"Eine Quallenart",
"Ein asiatisches Unternehmen",
"Etwas zum Schminken",
"Ein Bauteil des Computers",
"Ein Parfüm",
"Etwas, was man in der Handtasche findet",
"Ein Hersteller von Fahrrädern",
"Etwas, was man auf einer Radtour immer dabei haben sollte",
"Ein Agility-Hindernis",
"Ein Hersteller von Aufzügen",
"Eine Blumenart",
"Ein Kochutensil",
"Ein Putzuntensil",
"Ein Fastfood-Gericht",
"Ein Berg",
"Ein Mobilfunkanbieter",
"Ein bekanntes Gefängnis",
"Etwas für den Hund",
"Ein Fußballspieler",
"Ein Fußballverein",
"Ein bekannter Leichtathlet",
"Ein Olympiasieger",
"Ein bekannter Reiter",
"Eine Programmiersprache",
"Ein Lied, das man gut mitsingen kann",
"Ein bekanntes Instrumental-Lied",
"Etwas aus dem Wohnzimmer",
"Eine Bettenart",
"Ein bekanntes Straßenfest",
"Eine Fußkleidung",
"Ein Sternekoch",
"Eine Farbe",
"Ein Teil des Autos",
"Ein Zuebhör für Reiter",
"Eine Bootsklasse beim Rudern",
"Ein Hersteller von Elektronikgeräten",
"Ein Zubehör für den Vogelkäfig",
"Eine Schlangenart",
"Eine Märchengestalt",
"Ein Gas",
"Ein Getränk",
"Eine Sagengestalt",
"Ein Superheld",
"Eine Zeichentrickserie",
"Ein Betriebssystem",
"Eine Satirezeitschrift",
"Ein Dienstgrad beider Bundeswehr",
"Ein Gericht beim Italiener",
"Ein Gericht bei der Pommesbude",
"Eine Nachrichtensndung",
"Eine Stadt in NRW",
"Eine physikalische Einheit",
"Eine Währung",
"Ein türkischer Vorname",
"Ein Möbelhersteller",
"Etwas, was Du nachts machst",
"Ein Gericht von Subway",
"Eine mathematische Operation",
"Ein Verkehrsschild",
"Eine Zahl ausgeschrieben",
"Eine Hundefuttermarke",
"Eine Garungsform des Steaks",
"Ein mathematisches Gesetz",
"Ein Kamerahersteller",
"Ein Unternehmen aus Italien",
"Etwas, was du NICHT bei Mcdonalds bekommst",
"Ein Extremsport",
"Eine Schwimmtechnik",
"Eine Musikrichtung",
"Ein Musiker",
"Eine Supermarktkette",
"Ein Onlineshop",
"Eine Netzwerkkomponente",
"Ein alkoholisches Getränk",
"Ein alkoholfreies Getränk",
"Ein Actionfilm",
"Ein Ermittler aus einem Krimi",
"Etwas, was stinkt",
"Etwas, was jeder von uns zuhause hat",
"Ein Kinderlied",
"Ein Gefühl",
"Eine Baumart",
"Ein Obst",
"Ein Gemüse",
"Etwas, was man am Strand finden kann",
"Ein Planet",
"Ein Tier im Zoo",
"Etwas, was man im Zirkus sieht",
"Etwas, mit dem man sich aufwärmen kann"
]
